name: app_55hz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.92.0+10

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  hooks_riverpod: ^2.4.9
  freezed: ^2.4.6
  flutter_hooks: ^0.20.4
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  sign_button: ^2.0.0
  sign_in_with_apple: ^5.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  google_mobile_ads: ^4.0.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_udid: ^2.0.0
  flutter_picker: ^2.0.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.0.2
  url_launcher: ^6.0.18
  http: ^0.13.4
  pull_to_refresh: ^2.0.0
  package_info_plus: ^5.0.1
  image_picker: ^1.0.5
  rxdart: ^0.27.3
  state_notifier: ^1.0.0
  device_info: ^2.0.3
  version: ^3.0.2
  cached_network_image: ^3.3.0
  flutter_app_badger: ^1.5.0
  flutter_speed_dial: ^7.0.0
  record: ^5.0.4
  video_player: ^2.6.1
  algolia: ^1.1.2
  flutter_native_splash: ^2.2.16
  flutter_feather_icons: ^2.0.0+1
  go_router: ^13.0.1
  riverpod_annotation: ^2.3.3
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0

flutter_native_splash:
  image: 'images/icon.jpg' 
  color: '#FCFAF2'
  fullscreen: true
  android_12:
    icon_background_color: '#FCFAF2'
    image: 'images/icon.jpg'
    icon_background_color_dark: '#FCFAF2'
    image_dark: 'images/icon.jpg'

dependency_overrides:
  firebase_core_platform_interface: ^5.0.0
  intl: ^0.19.0


  
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.jpg"
  adaptive_icon_background: 'images/logobock.png'
  adaptive_icon_foreground: 'images/logo2.png'








dev_dependencies:
  flutter_lints: ^3.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  riverpod_generator:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/logo.gif
    - images/washi1.png
    - images/user.png

    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
