name: app_55hz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.92.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.5.1
  cloud_functions: ^3.3.9
  paginate_firestore: ^1.0.2
  firebase_core: ^1.24.0
  firebase_core_platform_interface: ^4.5.1
  firebase_auth: ^3.11.2
  firebase_storage: ^10.2.5
  firebase_analytics: ^9.3.8
  firebase_messaging: ^13.1.0
  sign_button: ^2.0.0
  sign_in_with_apple: ^4.3.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.0.4
  google_mobile_ads: ^2.1.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.11.0
  flutter_icons: ^1.0.0
  flutter_secure_storage: ^7.0.1
  flutter_slidable: ^0.6.0
  flutter_udid: ^2.0.0
  flutter_picker: ^2.0.1
  shared_preferences: ^2.0.13
  webview_flutter: ^4.0.2
  url_launcher: ^6.0.18
  http: ^0.13.4
  pull_to_refresh: ^2.0.0
  package_info_plus: ^3.0.2
  image_picker: ^0.8.6+1
  rxdart: ^0.27.3
  intl: ^0.17.0
  state_notifier: ^0.7.1
  device_info: ^2.0.3
  version: ^3.0.2
  cached_network_image: ^3.2.3
  flutter_app_badger: ^1.5.0
  flutter_speed_dial: ^6.2.0
  record: ^4.4.4
  audioplayers: ^3.0.1
  video_player: ^2.6.1
  algolia: ^1.1.2


dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  
 







  
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.jpg"
  adaptive_icon_background: 'images/logobock.png'
  adaptive_icon_foreground: 'images/logo2.png'








dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/logo.gif
    - images/washi1.png
    - images/user.png

    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
